name: windows-container-logger

on:
  push:
    branches: [ master ]
    paths:
      - hostprocess/containerd-logger/VERSION
  workflow_dispatch:
  pull_request:
    paths:
      - hostprocess/containerd-logger/**
    branches:
      - master

permissions:
  contents: read
  packages: write
jobs:
  image:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: set env
        run: |
          $version=Get-Content "hostprocess\containerd-logger\VERSION"
          echo "RELEASE_VERSION=$version" >> $env:GITHUB_ENV
      - name: login to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker build
        run: |
          docker build -t ghcr.io/kubernetes-sigs/sig-windows/eventflow-logger:${{ env.RELEASE_VERSION }} hostprocess\containerd-logger
      - name: docker push
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker push ghcr.io/kubernetes-sigs/sig-windows/eventflow-logger:${{ env.RELEASE_VERSION }}
