name: windows-eventflow-logger

on:
  push:
    branches: [ master ]
    paths:
      - hostprocess/eventflow-logger/VERSION
  workflow_dispatch:
  pull_request:
    paths:
      - hostprocess/eventflow-logger/**
    branches:
      - master

permissions:
  contents: read
  packages: write
jobs:
  image:
    runs-on: windows-2022
    env:
      image: ghcr.io/kubernetes-sigs/sig-windows/eventflow-logger
    steps:
      - uses: actions/checkout@v2
      - name: set release image
        run: |
          $version=Get-Content "hostprocess\eventflow-logger\VERSION"
          echo "RELEASE_IMAGE=${{ env.image }}:$version" >> $env:GITHUB_ENV
      - name: login to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: docker build
        run: |
          docker build -t ${{ env.RELEASE_IMAGE }}-1809 --build-arg=OS=1809 hostprocess\eventflow-logger
          docker build -t ${{ env.RELEASE_IMAGE }}-ltsc2022 --build-arg=OS=ltsc2022 hostprocess\eventflow-logger
      - name: docker push
        #if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker push ${{ env.RELEASE_IMAGE }}-1809
          docker push ${{ env.RELEASE_IMAGE }}-ltsc2022

          docker manifest create --amend ${{ env.RELEASE_IMAGE }} ${{ env.RELEASE_IMAGE }}-1809
          docker manifest annotate --os windows --arch amd64 --os-version 1809 ${{ env.RELEASE_IMAGE }} ${{ env.RELEASE_IMAGE }}-1809
          
          docker manifest create --amend ${{ env.RELEASE_IMAGE }} ${{ env.RELEASE_IMAGE }}-ltsc2022
          docker manifest annotate --os windows --arch amd64 --os-version ltsc2022 ${{ env.RELEASE_IMAGE }} ${{ env.RELEASE_IMAGE }}-ltsc2022
          
          docker manifest push --purge ${{ env.RELEASE_IMAGE }}
